// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggleoiwumxkutluxcopz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnbGVvaXd1bXhrdXRsdXhjb3B6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MzkyNjcsImV4cCI6MjA3MTExNTI2N30.rwzW_KVBXfboLWgPPSN1cwTAfQhlfsTJVgb8ViGYXK0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});